-- Custom plugins - each file calls vim.pack.add directly
require 'custom.plugins.claude'
require 'custom.plugins.codecompanion'
require 'custom.plugins.copilot'
require 'custom.plugins.leap'
require 'custom.plugins.neotest'
require 'custom.plugins.telescope_fb'
require 'custom.plugins.neovim_project'
require 'custom.plugins.toggleterm'
require 'custom.plugins.octo'
